image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - test

before_script:
  - apk add npm
  - npm install -g @apidevtools/swagger-cli

test:
  stage: test
  script:
    - swagger-cli validate src/index.html
